# Generated by Django 2.2.5 on 2020-10-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gps_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('vid', models.CharField(max_length=250)),
                ('lat', models.CharField(max_length=250)),
                ('lon', models.CharField(max_length=250)),
                ('speed', models.IntegerField(default=0)),
                ('unit_type', models.IntegerField(default=0)),
            ],
        ),
    ]
